### PR TITLE
fix: implement writeWithResponse in FakeStorageRpc

### PR DESCRIPTION
**Pull request by athakor**

### CODE REVIEW

**Review by dmitry-fa — COMMENTED** [review]
writeWithResponse is actually implemented in the StorageRpcTestBase class:

https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java

**Review by dmitry-fa — APPROVED** [review]
Oh, I see what the problem actually is.  Your change fixes it.
Not sure about version change in pom.xml. I think it's updating by bots...

**Comment by athakor** [comment]
> writeWithResponse is actually implemented in the StorageRpcTestBase class:
> 
> https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/testing/StorageRpcTestBase.java

@dmitry-fa yes correct but i think its not implement it in `FakeStorageRpc`.

**Comment by athakor** [comment]
> Not sure about version change in pom.xml. I think it's updating by bots...

no i guess because there is no any version related tag  `<!-- {x-version-update:google-cloud-storage:current} -->` here.

**Comment by dmitry-fa** [comment]
> 
> 
> > Not sure about version change in pom.xml. I think it's updating by bots...
> 
> no i guess because there is no any version related tag `<!-- {x-version-update:google-cloud-storage:current} -->` here.

I think you can go with a public PR

**Pull request closed without merging**
